# Imputation Function

In [1]:
import pandas as pd

In [2]:
X_df = pd.read_csv('../../data/prepared/train_data.csv')
X_df

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470739,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2017-11-06,0.730505,0.589866,0.051951,1.008380,0.008432,0.137431,0.000815,0.004927,...,NaN,NaN,NaN,0.005826,0.002661,0.006540,NaN,0.002191,0.001231,0.007120
470740,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2017-12-03,0.833949,0.005199,0.013103,1.005107,0.001183,0.134598,0.003260,0.001333,...,NaN,NaN,NaN,0.009753,0.009238,0.006315,NaN,0.009012,0.000864,0.005220
470741,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2018-01-16,0.837949,0.008265,0.013163,1.007224,0.005757,0.133852,0.005954,0.007394,...,NaN,NaN,NaN,0.008494,0.001622,0.009657,NaN,0.005007,0.008420,0.002532
470742,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2018-02-23,0.812465,0.002464,0.016056,1.003230,0.007137,0.136428,0.000088,0.009943,...,NaN,NaN,NaN,0.009720,0.009944,0.001952,NaN,0.007779,0.005021,0.005594
470743,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2018-03-31,0.844229,0.447585,0.028515,1.009867,0.001928,0.128707,0.003482,0.005893,...,NaN,NaN,NaN,0.007917,0.001520,0.005530,NaN,0.001430,0.003009,0.004843

In [3]:
y_df = pd.read_csv('../../data/prepared/train_labels.csv')
y_df

                                             customer_ID  target
0      e039c846adcb1bfd543d89b8beba6a0f1a2ecdf835cd22...       0
1      8a96ff0aacb31ab4aab4cd15f13e024c04f986b8926789...       0
2      cfe6ef5945ef9c04937bb1826ec350ae7f2d173867f7fe...       0
3      9b677e823a94355cf65d2b97930dd59fce82cbf69e82b8...       1
4      d48853a03d0d463a4b058d129453daaf530160ccc4f0c2...       0
...                                                  ...     ...
39002  79d17f1e1bee31fe1e1f9f6c69cadb8d1c9f6d6f7b9071...       0
39003  5bb1b40a1b26232d9140b8cab0f26639a54d2af554f6f6...       0
39004  8edaca5e3bfb75028c71f11b38d0cb1d7e2565277ec909...       1
39005  8d0f928ebe331f7e9bcf6b4bfed6f305328ebdebe8b7f4...       0
39006  636668de4796b40afae2bcd39f01a803f491effa499bec...       0

[39007 rows x 2 columns]

## Catagorical Imputation Function

In [4]:
def impute_categorical_columns(df):

    cat_columns = ['B_30', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_63', 'D_64', 'D_66', 'D_68']

    for column in cat_columns:

        if pd.api.types.is_numeric_dtype(df[column]):

            impute_value = df[column].value_counts().index.max() + 1

            df[column] = df[column].fillna(impute_value)

        else:

            impute_value = 'Unknown'

            df[column] = df[column].fillna(impute_value)
            
    return df

In [5]:
impute_categorical_columns(X_df)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470739,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2017-11-06,0.730505,0.589866,0.051951,1.008380,0.008432,0.137431,0.000815,0.004927,...,NaN,NaN,NaN,0.005826,0.002661,0.006540,NaN,0.002191,0.001231,0.007120
470740,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2017-12-03,0.833949,0.005199,0.013103,1.005107,0.001183,0.134598,0.003260,0.001333,...,NaN,NaN,NaN,0.009753,0.009238,0.006315,NaN,0.009012,0.000864,0.005220
470741,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2018-01-16,0.837949,0.008265,0.013163,1.007224,0.005757,0.133852,0.005954,0.007394,...,NaN,NaN,NaN,0.008494,0.001622,0.009657,NaN,0.005007,0.008420,0.002532
470742,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2018-02-23,0.812465,0.002464,0.016056,1.003230,0.007137,0.136428,0.000088,0.009943,...,NaN,NaN,NaN,0.009720,0.009944,0.001952,NaN,0.007779,0.005021,0.005594
470743,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,2018-03-31,0.844229,0.447585,0.028515,1.009867,0.001928,0.128707,0.003482,0.005893,...,NaN,NaN,NaN,0.007917,0.001520,0.005530,NaN,0.001430,0.003009,0.004843

In [6]:
null_dict = {
    'total_nulls': X_df.drop(columns='customer_ID').isna().sum(),
    'percent_nulls': X_df.drop(columns='customer_ID').isna().sum() / X_df.shape[0],
}

null_df = pd.DataFrame.from_dict(null_dict)
null_df

       total_nulls  percent_nulls
S_2              0       0.000000
P_2           3937       0.008363
D_39             0       0.000000
B_1              0       0.000000
B_2            188       0.000399
...            ...            ...
D_141         8390       0.017823
D_142       389671       0.827777
D_143         8390       0.017823
D_144         3376       0.007172
D_145         8390       0.017823

[189 rows x 2 columns]

## Imputation of Continuous Variables with less than 10% nulls

In [7]:
cat_columns = ['B_30', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_63', 'D_64', 'D_66', 'D_68']
date_column = 'S_2'
columns_to_drop = null_df[null_df.percent_nulls > .10].index.to_list() + cat_columns
columns_to_drop.append(date_column)
columns_to_drop

['S_3',
 'D_42',
 'D_43',
 'D_46',
 'D_48',
 'D_49',
 'D_50',
 'D_53',
 'S_7',
 'D_56',
 'S_9',
 'D_61',
 'D_62',
 'B_17',
 'D_73',
 'D_76',
 'D_77',
 'R_9',
 'D_82',
 'B_29',
 'D_87',
 'D_88',
 'D_105',
 'D_106',
 'R_26',
 'D_108',
 'D_110',
 'D_111',
 'B_39',
 'S_27',
 'B_42',
 'D_132',
 'D_134',
 'D_135',
 'D_136',
 'D_137',
 'D_138',
 'D_142',
 'B_30',
 'B_38',
 'D_114',
 'D_116',
 'D_117',
 'D_120',
 'D_126',
 'D_63',
 'D_64',
 'D_66',
 'D_68',
 'S_2']

In [9]:
X_df.drop(columns=columns_to_drop).groupby('customer_ID').median().fillna(-1)

,P_2,D_39,B_1,B_2,R_1,D_41,B_3,D_44,B_4,D_45,...,D_130,D_131,D_133,R_28,D_139,D_140,D_141,D_143,D_144,D_145
customer_ID,,,,,,,,,,,,,,,,,,,,,
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,0.938469,0.002483,0.013683,1.005006,0.004509,0.004653,0.007174,0.004128,0.038862,0.723293,...,0.005151,0.005653,0.005256,0.004462,0.003269,0.004516,0.005032,0.005810,0.005492,0.006362
0005ef1480ffe4f0e5908eae07db8e05f2e705bca6a57db3b97d1da2eb6c7cab,0.127632,0.473048,1.320220,0.016069,0.628908,0.005823,0.281365,0.444199,0.365449,0.137241,...,0.005401,0.002964,0.004017,0.004712,0.005775,0.007660,0.003014,0.002345,0.005643,0.005818
0005f2ab0cc352cd64eac9e60b981ed8c3289d20fa5fcef78973c468916fdfc9,0.894418,0.413056,0.033057,1.005275,0.008111,0.004556,0.003956,0.003006,0.067062,0.332743,...,0.006979,0.004535,0.004527,0.005414,0.006362,0.005014,0.006742,0.004801,0.005286,0.006505
0007ee1ac8edb6be588c6c8a158d2268e3228c49cf52773d168012076c118e5f,0.417593,0.006578,0.279894,0.042120,0.252183,0.004691,0.599639,0.880258,0.797802,0.123623,...,1.006111,0.990231,0.606251,0.003831,0.004402,0.003209,0.003429,0.003010,0.005844,0.004997
0008ef32824d3067b4d8ab70e7c79fa04c808f4d99194fe9c7827dac8bcf0b5c,0.843999,0.007834,0.004682,0.816315,0.004280,0.003278,0.005798,0.003209,0.146770,0.339671,...,0.005478,0.005672,0.004341,0.005264,0.005546,0.006200,0.004411,0.003544,0.004376,0.005424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ffeea21b8f17b728c561de93ea61e75547dd0216b36beba487c9ab3efa985fd5,0.879279,0.002782,0.022004,1.004305,0.004959,0.005903,0.004025,0.006007,0.047779,0.621031,...,0.006905,0.004858,0.005645,0.006118,0.003446,0.006050,0.006958,0.004439,0.003656,0.006024
ffeec9a34770713d0c488435fbff21db356407c98d9ddb37b535caa87979c61c,0.735560,0.007523,0.029760,1.005029,0.006797,0.004315,0.009938,0.005105,0.026333,0.151289,...,1.005862,0.003609,0.004255,0.006713,0.005608,0.006303,0.003806,0.005174,0.006798,0.006048
fff17a28a4594efc934648f3c33d295d452d61e2bda01df4b13952f48dfa1175,0.884326,0.007306,0.005870,0.814316,0.001679,0.003716,0.004301,0.003678,0.006787,0.021997,...,0.003826,0.004993,0.003770,0.003691,0.006811,0.005148,0.004464,0.007027,0.005466,0.006673
fffee056e120fb326c9413fca5a7ab6618cc49be9bb6b19c34f3fb13fd50fdd3,0.839127,0.008080,0.058885,0.819088,0.003032,0.008374,0.005807,0.005354,0.023588,0.066550,...,0.008079,0.004332,0.007668,0.005995,0.005018,0.005686,0.007297,0.004670,0.005194,0.005152
ffff41c8a52833b56430603969b9ca48d208e7c192c6a4081a6acc28cf4f8af7,0.859869,0.008375,0.028992,1.005107,0.005757,0.003482,0.005893,0.006297,0.041372,0.065939,...,0.005720,0.004066,0.003386,0.005480,0.008494,0.005766,0.005101,0.002001,0.006603,0.005594